# Run Prometheus setup only on the monitoring host
- name: Setup Prometheus server
  hosts: monitoring
  become: yes
  roles:
    - role: monitoring
      vars:
        install_prometheus: true
        install_node_exporter: false

# Run node_exporter setup on all hosts (including app, lb-db, monitor)
- name: Install node_exporter on all VMs
  hosts: all
  become: yes
  roles:
    - role: monitoring
      vars:
        install_prometheus: false
        install_node_exporter: true
