# Install and configure PostgreSQL database on the load balancer

- name: Ensure pip and dependencies are installed
  ansible.builtin.apt:
    name:
      - python3-pip
      - libpq-dev
      - python3-dev
    state: present
    update_cache: yes

- name: Install psycopg2 via pip
  ansible.builtin.pip:
    name: psycopg2-binary
    executable: pip3

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Allow postgres user local trust access (override existing rule)
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres'
    line: 'local   all             postgres                                trust'

- name: Allow postgres user IPv4 loop-back trust access
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    insertafter: '^# IPv4'
    regexp: '^host\s+all\s+postgres\s+127\.0\.0\.1/32'
    line: 'host    all             postgres        127.0.0.1/32            trust'

- name: Allow postgres user IPv6 loop-back trust access
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    insertafter: '^# IPv6'
    regexp: '^host\s+all\s+postgres\s+::1/128'
    line: 'host    all             postgres        ::1/128                 trust'

- name: Restart PostgreSQL to apply trust auth
  ansible.builtin.service:
    name: postgresql
    state: restarted
