- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root

- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: yes