- name: Include Prometheus setup
  include_tasks: prometheus.yml
  when: install_prometheus | default(false)

- name: Include Node Exporter setup
  include_tasks: node_exporter.yml
  when: install_node_exporter | default(false)

- name: Include Grafana setup
  include_tasks: grafana.yml
  when: install_grafana | default(false)

- name: Include Nginx reverse proxy for Grafana
  include_tasks: nginx.yml
  when: install_grafana | default(false)
