- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx reverse proxy for FastAPI
  ansible.builtin.template:
    src: fastapi_nginx.conf.j2
    dest: /etc/nginx/sites-available/fastapi
    mode: '0644'

- name: Enable Nginx config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/fastapi
    dest: /etc/nginx/sites-enabled/fastapi
    state: link
    force: yes

- name: Remove default Nginx site if exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
