- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: true
