---
- name: Deploy FastAPI app on Azure VM
  hosts: web
  become: yes
  vars:
    app_dir: /opt/fastapi_app

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install FastAPI and Uvicorn
      pip:
        name:
          - fastapi
          - "uvicorn[standard]"

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy FastAPI app to server
      copy:
        src: app/main.py
        dest: "{{ app_dir }}/main.py"
        mode: '0644'

    - name: Create systemd service for FastAPI
      copy:
        dest: /etc/systemd/system/fastapi.service
        content: |
          [Unit]
          Description=FastAPI Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 -m uvicorn main:app --host 127.0.0.1 --port 8000
          WorkingDirectory={{ app_dir }}
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: restart fastapi

  handlers:
    - name: restart fastapi
      systemd:
        name: fastapi
        state: restarted
        enabled: yes
